---
- name: Copy SSH KEY Administrator and Ansible
  hosts: Ubuntu,Rocky
  become: true
  vars:
   user_settings:
    Rocky:
      sudo_group: wheel
    Ubuntu:
      sudo_group: sudo
  tasks:
   - name: Create Ansible user
     ansible.builtin.user:
       name: ansible
      
   - name: Disable SSH root connection
     ansible.builtin.lineinfile:
             path: /etc/ssh/sshd_config
             regexp: '^PermitRootLogin'
             line: "PermitRootLogin no"

   - name: Disable autentication without password
     ansible.builtin.lineinfile:
             path: /etc/ssh/sshd_config
             regexp: '^PasswordAuthentication'
             line: "PasswordAuthentication no"

   - name: Convert ansible user without sudo password
     ansible.builtin.lineinfile:
       path: /etc/sudoers
       state: present
       line: 'ansible ALL=(ALL) NOPASSWD: ALL'
       insertafter: EOF

   - name: Generate SSH key pair for the ansible user
     ansible.builtin.openssh_keypair:
        path: /home/administrator/.ssh/ansible
        type: ed25519
        state: present
        comment: ansible@bastion

   - name: Set correct permissions for .ssh directory
     ansible.builtin.file:
       path: /home/administrator/.ssh
       mode: '0700'
       state: directory

   - name: Set correct permissions for the private key
     ansible.builtin.file:
       path: /home/administrator/.ssh/ansible
       mode: '0600'
       state: file

   - name: Copy Ansible user KEY
     ansible.builtin.authorized_key:
       user: ansible
       state: present
       key: "{{ lookup('file', '/home/administrator/.ssh/ansible.pub') }}"

