---
- name: Install Nginx
  hosts: Rocky
  become: true
  tasks:
   - name: Configure firewall for http
     firewalld:
      service: http
      permanent: yes
      state: enabled

   - name: Configure firewall for https
     firewalld:
      service: https
      permanent: yes
      state: enabled

   - name: Install OpenSSL for Self-signed certificate
     dnf:
      name: openssl
      state: present

   - name: Install python3-libsemanage for set boolean
     dnf:
      name: python3-libsemanage
      state: present

   - name: Install Nginx
     dnf:
      name: nginx
      state: present

   - name: Create directory for certificate
     file:
      path: /etc/nginx/ssl
      state: directory
      mode: '0775'

   - name: Copy Nginx configuration
     template:
      src: /home/administrator/tallerfebrero2024/Inventories_UsuarioAnsible/jinja/nginx.conf.j2
      dest: /etc/nginx/nginx.conf

   - name: Generate SSL certificate and key
     command: "sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/nginx-selfsigned.key -out /etc/nginx/ssl/nginx-selfsigned.crt -subj '/C=UY/ST=MVD/L=MVD/O=TallerLinux2024/OU=LinuxServer/CN=ServerB.local'"

   - name: Set boolean for SELinux to enable httpd_can_network_connect
     seboolean:
      name: httpd_can_network_connect
      state: yes
      persistent: yes

   - name: Restart firewalld service
     service:
       name: firewalld
       state: restarted

   - name: Restart nginx service
     service:
       name: nginx
       state: restarted
