---
- name: Update Ubuntu and Rocky Linux
  hosts: all
  become: yes
  tasks:
    - name: Update Ubuntu packages
      when: ansible_distribution == 'Ubuntu'
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 3600

    - name: Update Rocky Linux packages
      when: ansible_distribution == 'Rocky'
      dnf:
        name: '*'
        state: latest

