---
- name: Deploy docker container
  hosts: Ubuntu
  become: true

  tasks:
    - name: Copy war to server
      copy:
       src: /home/administrator/tallerfebrero2024/Tomcat8/sample.war
       dest: /home/ansible/sample.war

    - name: Create Docker container for Tomcat 8
      docker_container:
        name: WebappTallerLinux
        image: tomcat:8-jdk8
        state: started
        ports:
          - "8080:8080"
        volumes:
          - "/home/ansible:/usr/local/tomcat/webapps"
        restart_policy: always
