---
- name: Copy SSH KEY Administrator and Ansible
  hosts: all
  become: true
  vars:
   user_settings:
    Rocky:
      sudo_group: wheel
    Ubuntu:
      sudo_group: sudo
  tasks:
   - name: Create Ansible user
     ansible.builtin.user:
       name: ansible
      
   - name: Disable SSH root connection
     ansible.builtin.lineinfile:
             path: /etc/ssh/sshd_config
             regexp: '^PermitRootLogin'
             line: "PermitRootLogin no"

   - name: Disable autentication without password
     ansible.builtin.lineinfile:
             path: /etc/ssh/sshd_config
             regexp: '^PasswordAuthentication'
             line: "PasswordAuthentication no"

   - name: Convert ansible user without sudo password
     ansible.builtin.lineinfile:
       path: /etc/sudoers
       state: present
       line: 'ansible ALL=(ALL) NOPASSWD: ALL'
       insertafter: EOF

   - name: Ensure .ssh directory exists for ansible user
     ansible.builtin.file:
       path: "/home/ansible/.ssh"
       state: directory
       owner: ansible
       group: ansible
       mode: '0700'
         
   - name: Generar clave SSH Ed25519 para el usuario ansible
     ansible.builtin.openssh_keypair:
       path: "/home/ansible/.ssh/id_ed25519"  # Ruta donde se generará la clave SSH para el usuario ansible
       state: present        
       type: ed25519                          # Tipo de clave SSH
       owner: ansible                         # Dueño del archivo de clave
       group: ansible                         # Grupo del archivo de clave
       mode: '0600'                           # Permisos del archivo de clave
     become: yes

   - name: Copy Ansible user KEY
     ansible.builtin.authorized_key:
       user: ansible
       state: present
       key: "{{ lookup('file', '/home/administrator/.ssh/ansible.pub') }}"
